### ISSUE TITLE
Java related error while running ./kotcity.sh

### ISSUE THREAD

**Issue by WPFilmmaker** [kotcity/kotcity#63]
I think I have all the necessary java packages installed. This is what I do to try to run kotcity:

myname@mynamepc:~/Downloads/kotcity-pre-alpha-0.49.2$ chmod +x kotcity.sh

myname@mynamepc:~/Downloads/kotcity-pre-alpha-0.49.2$ ./kotcity.

I get:

```
Exception in thread "main" java.lang.NoClassDefFoundError: javafx/application/Application
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
    at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
    at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at kotcity.ui.LaunchScreenKt.main(LaunchScreen.kt:95)
Caused by: java.lang.ClassNotFoundException: javafx.application.Application
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 25 more
```

Any idea?

**Comment by kotcity** [comment]
A very good idea. This appears to be JavaFX missing. If you are on Ubuntu or similar, see this section under the readme "apt-get install openjfx".

If that doesn't work, get Oracle JDK and it should work. However, OpenJDK is supported and you should be able to remedy with the installation of openjfx.

**Comment by kotcity** [comment]
Actually, if it still doesn't work, please send back information on your distro and output of 

"java -version"

**Comment by WPFilmmaker** [comment]
@kotcity Your suggestion of installing openjfx worked thanks!

I have openjdk 8 installed and this is the output for "java -version"

`myname@mynamepc:~$
openjdk version "1.8.0_162"
OpenJDK Runtime Environment (build 1.8.0_162-8u162-b12-0ubuntu0.16.04.2-b12)
OpenJDK 64-Bit Server VM (build 25.162-b12, mixed mode)`

**Comment by kotcity** [comment]
Cool. As this is already covered in the README I'm calling this case closed.
